# Generated by Django 4.1 on 2022-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('page_count', models.IntegerField(default=0)),
                ('image_url', models.CharField(max_length=256, null=True)),
                ('short_description', models.CharField(max_length=256, null=True)),
                ('long_description', models.TextField(null=True)),
            ],
        ),
    ]
